version: "3.7"
services:
  ui:
    container_name: home_server_ui
    build: ./ui
    restart: always
    ports:
      - 80:80
    depends_on:
      - db
  node:
    container_name: home_server_node
    build: ./node
    volumes: 
      - ./node/dist:/app/dist
    ports:
      - 4000:4000
      - 5858:5858
    env_file:
      - ./node/.env
    depends_on:
      - db
  db:
    container_name: home_server_mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    env_file:
      - ./mongo.env
