version: "3.7"
services:
  hs_ui:
    container_name: hs_ui
    build: ./ui
    restart: always
    ports:
      - 80:80
    depends_on:
      - hs_node
      - hs_mongo
  hs_node:
    container_name: hs_node
    build: ./node
    restart: always
    volumes: 
      - ./node/dist:/app/dist
    ports:
      - '4000:4000'
      - '5858:5858'
    env_file:
      - ./node/.env
    depends_on:
      - hs_mongo
      - hs_mqtt
  hs_mongo:
    container_name: hs_mongo
    image: mongo
    restart: always
    volumes: 
      - ./mongo/data:/data/db
    ports:
      - '27017:27017'
    env_file:
      - ./mongo/.env
  hs_mqtt:
    container_name: hs_mqtt
    image: eclipse-mosquitto
    restart: always
    ports:
      - '1883:1883'
      - '9001:9001'