version: "3.7"
services:
  hs_ui:
    container_name: hs_ui
    build: ./ui
    restart: always
    ports:
      - 80:80
    depends_on:
      - hs_node
      - hs_postgres
  hs_node:
    container_name: hs_node
    build: ./node
    restart: always
    volumes: 
      - ./node/dist:/app/dist
    ports:
      - '4000:4000'
      - '5858:5858'
    environment:
      - POSTGRES_URL=hs_postgres
    env_file:
      - ./node/.env
    depends_on:
      - hs_postgres
      - hs_mqtt
  hs_postgres:
    container_name: hs_postgres
    image: postgres
    restart: always
    volumes: 
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    env_file:
      - ./postgres/.env
  hs_mqtt:
    container_name: hs_mqtt
    image: eclipse-mosquitto
    restart: always
    ports:
      - '1883:1883'
      - '9001:9001'
