import React from "react";
import { useOverviewQuery } from "./autogenerated-apollo";

export const Overview: React.FC = () => {
  const { data, error, loading } = useOverviewQuery();

  if (loading || error || !data || !data.hvacValues) return null;

  return (
    <code>
      {data.hvacValues.map(x => (
        <pre key={x._id}>
          {x.source} - {x.temperatureValue} :: {x.humidityValue}
        </pre>
      ))}
      <pre>{JSON.stringify(data, null, 2)}</pre>
    </code>
  );
};
