FROM node
WORKDIR /app

# install nodemon for DEV environment
RUN yarn global add nodemon

# copy app and build
COPY ./package.json /app/package.json
RUN yarn 
COPY . /app

CMD ["nodemon", "--inspect=0.0.0.0:5858", "./dist/index.js"]